services:
  loja-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=LojaDB;User=sa;Password=Api@123;TrustServerCertificate=True;
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=LojaDoSeuManoelDb;User Id=sa;Password=Api@12345678#;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Api@12345678#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
